# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: coredns-plus

before:
  hooks:
    - go mod tidy
    - go mod download

gomod:
  proxy: true
  env:
    - GOPRIVATE=github.com/ccie57654/*

builds:
  - main: main.go
    flags:
      - -trimpath
      - -work
      - -v
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    mod_timestamp: "{{ .CommitTimestamp }}"
    tags:
      - osusergo
      - netgo
      - static_build
    ldflags:
      - "-s -w -extldflags '-static' -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

source:
  enabled: true
  name_template: "{{ .ProjectName }}.src"

archives:
  - formats: [tar.gz]
    wrap_in_directory: true
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64keyless
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    builds_info:
      mtime: "{{ .CommitTimestamp }}"
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

sboms:
  - artifacts: archive
    args: ["$artifact", "--output", "cyclonedx-json=$document"]
  - id: source
    artifacts: source
    args: ["$artifact", "--output", "cyclonedx-json=$document"]

signs:
  - id: cosign_checksums
    cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - "sign-blob"
      - "--bundle=${signature}"
      - "${artifact}"
    artifacts: checksum
    output: true

dockers_v2:
- id: gitaction
  dockerfile: Dockerfile
  images:
    - ghcr.io/ccie57654/${{ .ProjectName }}
  sbom: true
  tags:
    - "{{ .Tag }}"
  labels:
    "org.opencontainers.image.description": "Custom compilation of CoreDNS"
    "org.opencontainers.image.created": "{{.Date}}"
    "org.opencontainers.image.name": "{{.ProjectName}}"
    "org.opencontainers.image.revision": "{{.FullCommit}}"
    "org.opencontainers.image.version": "{{.Version}}"
    "org.opencontainers.image.source": "{{.GitURL}}"
  platforms:
    - linux/amd64
    - linux/arm64
  flags:
    - "--provenance=true"

docker_signs:
  - cmd: cosign
    output: true
    args:
      - "sign"
      - "${artifact}"
      - "--yes"