# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: coredns-plus

before:
  hooks:
    - go mod tidy
    - go mod download

gomod:
  proxy: true
  env:
    - GOPRIVATE=github.com/ccie57654/*
  mod: mod

builds:
  - main: main.go
    flags:
    - -work
    - -v
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    tags:
      - osusergo
      - netgo
      - static_build
    ldflags:
      - "-s -w -extldflags '-static'"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

dockers_v2:
- id: gitaction
  dockerfile: Dockerfile.github
  images:
    - ghcr.io/ccie57654/${{ .ProjectName }}
  sbom: true
  tags:
    - "v{{ .Version }}"
    - "latest"
  labels:
    "org.opencontainers.image.description": "Custom compilation of CoreDNS"
    "org.opencontainers.image.created": "{{.Date}}"
    "org.opencontainers.image.name": "{{.ProjectName}}"
    "org.opencontainers.image.revision": "{{.FullCommit}}"
    "org.opencontainers.image.version": "{{.Version}}"
    "org.opencontainers.image.source": "{{.GitURL}}"
  platforms:
    - linux/amd64
    - linux/arm64
- id: localtest
  dockerfile: Dockerfile
  images:
    - ccie57654/${{ .ProjectName }}
  sbom: false
  tags:
    - "v{{ .Version }}"
    - "latest"
  labels:
    "org.opencontainers.image.description": "Custom compilation of CoreDNS"
    "org.opencontainers.image.created": "{{.Date}}"
    "org.opencontainers.image.name": "{{.ProjectName}}"
    "org.opencontainers.image.revision": "{{.FullCommit}}"
    "org.opencontainers.image.version": "{{.Version}}"
    "org.opencontainers.image.source": "{{.GitURL}}"
  platforms:
    - linux/amd64
  flags:
    - "--provenance=false"

checksum:
  name_template: '{{ .ArtifactName }}.{{ .Algorithm }}'
  algorithm: sha256
  split: true

sboms:
  - artifacts: binary
    documents: ["{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.sbom.json"]
    cmd: syft
    args: ["$artifact", "--output", "cyclonedx-json=$document"]

signs:
  - id: checksum_sigs
    artifacts: checksum
    signature: "${artifact}.sig"
    cmd: gpg
    args: ["--output", "${signature}", "--detach-sign", "${artifact}"]
  - id: sbom_sigs
    artifacts: sbom
    signature: "${artifact}.sig"
    cmd: gpg
    args: ["--output", "${signature}", "--detach-sign", "${artifact}"]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
